version: '3'

services:
  db:
    image: postgres:13  # You can choose the desired PostgreSQL version
    container_name: postgres-db
    environment:
      POSTGRES_DB: yourdbname
      POSTGRES_USER: yourdbuser
      POSTGRES_PASSWORD: yourdbpassword
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"  # Map the PostgreSQL port

volumes:
  postgres-data:
