# Generated by Django 4.2.4 on 2023-09-06 11:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EndDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StartDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('startDate', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee', models.CharField(max_length=100)),
                ('department', models.CharField(max_length=100)),
                ('endDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_register.enddate')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_register.name')),
                ('startDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emp_register.startdate')),
            ],
        ),
    ]
