# Generated by Django 4.2.4 on 2023-09-06 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emp_register', '0002_department_alter_salary_enddate_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salary',
            name='endDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='salary',
            name='startDate',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='EndDate',
        ),
        migrations.DeleteModel(
            name='StartDate',
        ),
    ]
